name: TunnelBear IP Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape-tunnelbear-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          echo "Installing Google Chrome..."
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d " " -f 3 | cut -d "." -f 1)
          echo "Detected Chrome version: $CHROME_VERSION"

          echo "Installing ChromeDriver..."
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"

          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver-linux64.zip"
          unzip -o chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver-linux64.zip chromedriver-linux64
          
      - name: Run TunnelBear IP Scraper
        run: python main.py
        env:
          tunnelbear_email: ${{ secrets.TUNNELBEAR_EMAIL }}
          tunnelbear_password: ${{ secrets.TUNNELBEAR_PASSWORD }}
          
      - name: Run IP Validation
        run: python validate_ips.py
        
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tunnelbear_ips.json tunnelbear_ips.txt tunnelbear_ips_ttl.json
          git commit -m "Update TunnelBear IPs [skip ci]" || echo "No changes to commit"
          git push