name: TunnelBear IP Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape-tunnelbear-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          echo "Installing Google Chrome..."
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          echo "Fetching latest ChromeDriver version..."
          # Get the XML listing from storage API
          CHROME_DRIVER_XML=$(curl -s "https://chromedriver.storage.googleapis.com/")
          
          # Extract all Linux versions using grep and sort to get the latest
          LATEST_VERSION=$(echo "$CHROME_DRIVER_XML" | grep -o '<Key>[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*/chromedriver_linux64\.zip</Key>' | 
                          sed -E 's/<Key>([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).+<\/Key>/\1/' | 
                          sort -t. -k1,1n -k2,2n -k3,3n -k4,4n | 
                          tail -1)
          
          echo "Latest ChromeDriver version: $LATEST_VERSION"
          
          # Download and install the latest version
          wget -q "https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip"
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver_linux64.zip
          chromedriver --version

      - name: Run TunnelBear IP Scraper
        run: python main.py
        env:
          tunnelbear_email: ${{ secrets.TUNNELBEAR_EMAIL }}
          tunnelbear_password: ${{ secrets.TUNNELBEAR_PASSWORD }}
          
      - name: Run IP Validation
        run: python validate_ips.py
        
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tunnelbear_ips.json tunnelbear_ips.txt tunnelbear_ips_ttl.json
          git commit -m "Update TunnelBear IPs [skip ci]" || echo "No changes to commit"
          git push