name: TunnelBear IP Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape-tunnelbear-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run TunnelBear IP Scraper
        run: python main.py
        env:
          tunnelbear_email: ${{ secrets.TUNNELBEAR_EMAIL }}
          tunnelbear_password: ${{ secrets.TUNNELBEAR_PASSWORD }}

      - name: Run IP Validation
        run: python validate_ips.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tunnelbear_ips.json tunnelbear_ips.txt tunnelbear_ips_ttl.json
          git commit -m "Update TunnelBear IPs [skip ci]" || echo "No changes to commit"
          git push